<?php
/**
 * ACF fields for Product Description.
 *
 * @package WagnerSprayTech\Core
 */

$fields = [
	[
		'show_column_filter'   => false,
		'allow_bulkedit'       => false,
		'allow_quickedit'      => false,
		'show_column'          => false,
		'show_column_weight'   => 1000,
		'show_column_sortable' => false,
		'key'                  => 'wst_product_feature_list',
		'label'                => 'Feature List',
		'name'                 => 'feature_list',
		'aria-label'           => '',
		'type'                 => 'repeater',
		'instructions'         => '',
		'required'             => 0,
		'conditional_logic'    => 0,
		'wrapper'              => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'layout'               => 'table',
		'pagination'           => 0,
		'min'                  => 0,
		'max'                  => 0,
		'collapsed'            => '',
		'button_label'         => 'Add Feature',
		'rows_per_page'        => 20,
		'sub_fields'           => [
			[
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'wst_product_feature_list_item',
				'label'                => '',
				'name'                 => 'item',
				'aria-label'           => '',
				'type'                 => 'text',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'        => '',
				'maxlength'            => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'parent_repeater'      => 'field_649b0b601a96e',
			],
		],
	],
	[
		'show_column_filter'   => false,
		'allow_bulkedit'       => true,
		'allow_quickedit'      => true,
		'show_column'          => false,
		'show_column_weight'   => 1000,
		'show_column_sortable' => false,
		'key'                  => 'wst_product_short_tag',
		'label'                => 'Tag Line',
		'name'                 => 'tag_line',
		'aria-label'           => '',
		'type'                 => 'text',
		'instructions'         => '',
		'required'             => 0,
		'conditional_logic'    => 0,
		'wrapper'              => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'relevanssi_exclude'   => 0,
		'default_value'        => '',
		'maxlength'            => '',
	],
	[
		'show_column_filter'   => false,
		'allow_bulkedit'       => false,
		'allow_quickedit'      => false,
		'show_column'          => false,
		'show_column_weight'   => 1000,
		'show_column_sortable' => false,
		'key'                  => 'wst_product_short_description',
		'label'                => 'Short Description',
		'name'                 => 'short_description',
		'aria-label'           => '',
		'type'                 => 'wysiwyg',
		'instructions'         => '',
		'required'             => 0,
		'conditional_logic'    => 0,
		'wrapper'              => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'relevanssi_exclude'   => 0,
		'default_value'        => '',
		'maxlength'            => '',
		'rows'                 => '',
		'placeholder'          => '',
		'new_lines'            => '',
	],
	[
		'show_column_filter'   => false,
		'allow_bulkedit'       => false,
		'allow_quickedit'      => false,
		'show_column'          => false,
		'show_column_weight'   => 1000,
		'show_column_sortable' => false,
		'key'                  => 'wst_product_long_description',
		'label'                => 'Features',
		'name'                 => 'long_description',
		'aria-label'           => '',
		'type'                 => 'wysiwyg',
		'instructions'         => '',
		'required'             => 0,
		'conditional_logic'    => 0,
		'wrapper'              => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'relevanssi_exclude'   => 0,
		'default_value'        => '',
		'tabs'                 => 'all',
		'toolbar'              => 'full',
		'media_upload'         => 1,
		'delay'                => 0,
	],
	[
		'key'               => 'wst_product_add_to_cart',
		'label'             => 'Add to Cart',
		'name'              => 'add_to_cart',
		'type'              => 'url',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_add_to_cart_pixel',
		'label'             => 'Add to Cart Pixel',
		'name'              => 'add_to_cart_pixel',
		'type'              => 'url',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_keywords',
		'label'             => 'Search Keywords',
		'name'              => 'keywords',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
];

$location = [
	[
		[
			'param'    => 'post_type',
			'operator' => '==',
			'value'    => 'product',
		],
	],
];


acf_add_local_field_group(
	[
		'key'                   => 'wst_product_description_group',
		'title'                 => 'Product Description',
		'fields'                => $fields,
		'location'              => $location,
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 1,
	]
);
