<?php
/**
 * ACF fields for Product CPT.
 *
 * @package WagnerSprayTech\Core
 */

$fields = [
	[
		'key'               => 'wst_product_sku',
		'label'             => 'SKU',
		'name'              => 'sku',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_id',
		'label'             => 'Product ID',
		'name'              => 'id',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_price',
		'label'             => 'Price',
		'name'              => 'price',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_upc',
		'label'             => 'UPC',
		'name'              => 'upc',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_weight',
		'label'             => 'Weight',
		'name'              => 'weight',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_unit',
		'label'             => 'Unit',
		'name'              => 'unit',
		'type'              => 'text',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'default_value'     => '',
		'placeholder'       => '',
		'prepend'           => '',
		'append'            => '',
		'maxlength'         => '',
	],
	[
		'key'               => 'wst_product_inventory_status',
		'label'             => 'Inventory Status',
		'name'              => 'inventory_status',
		'type'              => 'true_false',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'message'           => '',
		'default_value'     => 0,
		'ui'                => 1,
		'ui_on_text'        => '',
		'ui_off_text'       => '',
	],
	[
		'key'               => 'wst_product_purchasable',
		'label'             => 'Purchasable',
		'name'              => 'purchasable',
		'type'              => 'true_false',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'message'           => '',
		'default_value'     => 0,
		'ui'                => 1,
		'ui_on_text'        => '',
		'ui_off_text'       => '',
	],
	[
		'key'               => 'wst_product_displayable',
		'label'             => 'Displayable',
		'name'              => 'displayable',
		'type'              => 'true_false',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'message'           => '',
		'default_value'     => 0,
		'ui'                => 1,
		'ui_on_text'        => '',
		'ui_off_text'       => '',
	],
	[
		'key'               => 'wst_product_prop_65_lead',
		'label'             => 'Prop 65 lead',
		'name'              => 'prop_65_lead',
		'type'              => 'true_false',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'message'           => '',
		'default_value'     => 0,
		'ui'                => 1,
		'ui_on_text'        => '',
		'ui_off_text'       => '',
	],
	[
		'key'               => 'wst_product_prop_65_wood',
		'label'             => 'Prop 65 Wood',
		'name'              => 'proo_65_wood',
		'type'              => 'true_false',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'message'           => '',
		'default_value'     => 0,
		'ui'                => 1,
		'ui_on_text'        => '',
		'ui_off_text'       => '',
	],
	[
		'key'               => 'wst_product_needs_restricted_shipping_option',
		'label'             => 'Restricted Shipping Option',
		'name'              => 'needs_restricted_shipping_option',
		'type'              => 'true_false',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => [
			'width' => '',
			'class' => '',
			'id'    => '',
		],
		'message'           => '',
		'default_value'     => 0,
		'ui'                => 1,
		'ui_on_text'        => '',
		'ui_off_text'       => '',
	],
];

$location = [
	[
		[
			'param'    => 'post_type',
			'operator' => '==',
			'value'    => 'product',
		],
	],
	[
		[
			'param'    => 'post_type',
			'operator' => '==',
			'value'    => 'part',
		],
	],
];


acf_add_local_field_group(
	[
		'key'                   => 'wst_product_details_group',
		'title'                 => 'Product Details',
		'fields'                => $fields,
		'location'              => $location,
		'menu_order'            => 1,
		'position'              => 'side',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 1,
	]
);
